name: run-tests

on:
  push:
    branches: [master]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [3.6.x, 3.7.x]

    name: Python ${{ matrix.python }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install dependencies
        run: |
          sudo apt-get install -y \
            gir1.2-glib-2.0 \
            libffi-dev \
            libgirepository1.0-dev \
            libglib2.0-dev
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Run tests
        run: python setup.py test
